### ISSUE TITLE
The NlpCloud seems to be down

### ISSUE THREAD

**Issue by hshahdoost** [adobe/NLP-Cube#121] opened 2021-01-02 15:59 UTC
**Describe the bug**
Apparently the nlp cloud at `http://nlp-cube.speed.pub.ro/models/` is out of service

**To Reproduce**
Run the following commands

```
from cube.api import Cube

nlp_cube = Cube()
nlp_cube.load("en")
```
**Expected behavior**
It's expected that the cube library downloads the modules from it's cloud path

**Comment by tiberiu44** [comment] 2021-01-02 20:31
Hi @hshahdoost 

Thanks for letting us know. We will contact our hosting partners and try to solve this as fast as possible.

**Comment by hshahdoost** [comment] 2021-01-03 08:53
Thanks for the awesome library, I'm just one of the many users :-)

**Comment by dumitrescustefan** [comment] 2021-01-04 10:16
Hi, the problem is due to some hardware failure at the provider we're hosting our models at. We've been told that the ETA to bring the infrastructure up is hopefully today (4th Jan), or at most tomorrow.

Thanks for the patience!

**Comment by dumitrescustefan** [comment] 2021-01-04 12:51
Hosting problem seems to be solved, closing now. Please reopen if it isn't working for you.

**Closed by dumitrescustefan** 2021-01-04 12:51 UTC
